version: "3.1"
networks:
    laravel:
      driver: bridge

services: 
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
      - mysql
    networks: 
      - laravel

  php:
    container_name: php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  mysql:
    container_name: mysql
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'bdairam'
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'develop'
      MYSQL_PASSWORD: 'poleved'
    networks: 
      - laravel

volumes:
  db:
    driver: local

